<?php
/**
 * UserInfoReqTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/Swagger-api/Swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/Swagger-api/Swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 * Generated by: https://github.com/Swagger-api/Swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the Swagger code generator program.
 * https://github.com/Swagger-api/Swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserInfoReqTest Class Doc Comment
 *
 * @category    Class
 * @description UserInfoReq
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/Swagger-api/Swagger-codegen
 */
class UserInfoReqTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserInfoReq"
     */
    public function testUserInfoReq()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
