/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
}(this, function(expect, SwaggerJsClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserSearchReq', function() {
      beforeEach(function() {
        instance = new SwaggerJsClient.UserSearchReq();
      });

      it('should create an instance of UserSearchReq', function() {
        // TODO: update the code to test UserSearchReq
        expect(instance).to.be.a(SwaggerJsClient.UserSearchReq);
      });

      it('should have the property keyWord (base name: "keyWord")', function() {
        // TODO: update the code to test the property keyWord
        expect(instance).to.have.property('keyWord');
        // expect(instance.keyWord).to.be(expectedValueLiteral);
      });

    });
  });

}));
